name: 打包Mac软件
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install pillow py2app

      - name: 生成打包配置
        run: |
          py2applet --make-setup photo_ya_suo.py

      - name: 开始打包Mac APP
        run: |
          python setup.py py2app

      - name: 上传打包好的软件
        uses: actions/upload-artifact@v4
        with:
          name: MyMacApp
          path: dist/*.app
